### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by HoschkeMelanie** [markusbegerow/ChatGPT.PromptEngineering#1]
HI @markusbegerow,

thank you so much for the plugin. Since a few days the plugin does not work properly and the button is no longer displayed. I found the following error message: 

Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': 'flex flex-col w-full py-[10px] flex-grow md:py-4 md:pl-4' is not a valid selector.

![image](https://github.com/markusbegerow/ChatGPT.PromptEngineering/assets/134927424/d9ded14c-fd89-4799-9397-40f673c34e9a)

**Comment by markusbegerow** [comment]
Hey @HoschkeMelanie,

i will look into it. Maybe somethin' has changed on the openai site.

**Comment by markusbegerow** [comment]
Now it works again.
